name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sub-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Notify Start on Discord
        run: |
          TIMESTAMP=$(TZ=Asia/Manila date +"%Y-%m-%d %H:%M:%S %Z %z")
          MESSAGE="**üõ†Ô∏è Build Started**\n\n"
          MESSAGE+="**üì¶ Repository:** ${{ github.repository }}\n\n"
          MESSAGE+="**üå± Branch:** ${{ github.ref }}\n\n"
          MESSAGE+="**üïí Triggered at:** ${TIMESTAMP}"
          JSON_PAYLOAD=$(jq -n --arg content "$MESSAGE" '{"content":$content}')
          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD"


      - name: Build and Push Image
        run: |
          docker buildx build --platform linux/amd64 \
          -t ghcr.io/${{ github.actor }}/docker-chrome:latest --push .

      - name: Notify Success on Discord
        if: success()
        run: |
          TIMESTAMP=$(TZ=Asia/Manila date +"%Y-%m-%d %H:%M:%S %Z %z")
          MESSAGE="**‚úÖ Build Done**\n"
          MESSAGE+="**üì¶ Repository:** ${{ github.repository }}\n"
          MESSAGE+="**üå± Branch:** ${{ github.ref }}\n"
          MESSAGE+="**üïí Completed at:** ${TIMESTAMP}"
          JSON_PAYLOAD=$(jq -n --arg content "$MESSAGE" '{"content":$content}')
          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD"

      - name: Notify Failure on Discord
        if: failure()
        run: |
          TIMESTAMP=$(TZ=Asia/Manila date +"%Y-%m-%d %H:%M:%S %Z %z")
          MESSAGE="**‚ùå Build Error**\n"
          MESSAGE+="**üì¶ Repository:** ${{ github.repository }}\n"
          MESSAGE+="**üå± Branch:** ${{ github.ref }}\n"
          MESSAGE+="**üïí Failed at:** ${TIMESTAMP}"
          JSON_PAYLOAD=$(jq -n --arg content "$MESSAGE" '{"content":$content}')
          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD"
